// Palate beer catalog — static reference for log-sheet autocomplete.
// Each entry: { name, style (a leaf style id), notes }. No brewery field — the
// brewery is part of the name as it appears on a menu (e.g. "Corona Extra").
// 506 beers across 57 styles, weighted toward what you'd
// actually find at well-rated breweries, beer bars, and restaurants (esp. NYC & SF).
window.CATALOG = [
  {"name":"21st Amendment Brew Free! or Die IPA","style":"west-coast-ipa","notes":"Tropical citrus, balanced bitterness"},
  {"name":"21st Amendment Down to Earth IPA","style":"session-ipa","notes":"Tropical citrus, low-ABV session"},
  {"name":"3 Fonteinen Oude Geuze","style":"lambic","notes":"Refined, complex, dry oak funk"},
  {"name":"Abita Amber","style":"american-amber","notes":"Smooth Munich malt, Louisiana lager"},
  {"name":"Abita Purple Haze","style":"fruit-wheat","notes":"Raspberry-infused, tart, pink Louisiana wheat"},
  {"name":"Aecht Schlenkerla Rauchbier Märzen","style":"rauchbier","notes":"Intense smoke, bacon, toasty malt"},
  {"name":"Affligem Blonde","style":"belgian-blonde","notes":"Bready malt with gentle fruit and spice"},
  {"name":"Affligem Tripel","style":"tripel","notes":"Bready, fruity, lightly spiced"},
  {"name":"Alaskan Amber","style":"altbier","notes":"Malty altbier, smooth toasty finish"},
  {"name":"AleSmith IPA","style":"west-coast-ipa","notes":"Grapefruit, pine, clean dry finish"},
  {"name":"AleSmith Speedway Stout","style":"imperial-stout","notes":"Coffee, chocolate, rich roast"},
  {"name":"AleSmith Wee Heavy","style":"wee-heavy","notes":"Caramel, toffee, malty richness"},
  {"name":"Allagash Coolship Resurgam","style":"lambic","notes":"Spontaneous Maine gueuze, bright and funky"},
  {"name":"Allagash Dubbel","style":"dubbel","notes":"Dark fruit, malty, subtly sweet"},
  {"name":"Allagash Saison","style":"saison","notes":"Rye spice, tropical fruit, peppery"},
  {"name":"Allagash Tripel","style":"tripel","notes":"Honeyed, fruity, warming, complex"},
  {"name":"Allagash White","style":"witbier","notes":"Coriander, citrus, spicy Maine flagship"},
  {"name":"Almanac Sournova","style":"fruited-sour","notes":"Fruited kettle sour, juicy tart"},
  {"name":"Alpine Beer Co Duet IPA","style":"west-coast-ipa","notes":"Amarillo, Simcoe, balanced citrus"},
  {"name":"Amstel Light","style":"euro-pale-lager","notes":"Light Dutch lager, clean and dry"},
  {"name":"Anchor Old Foghorn Barleywine","style":"american-barleywine","notes":"Toffee, dried fruit, warming"},
  {"name":"Anchor Porter","style":"porter","notes":"Dark caramel, toffee, roasted malt"},
  {"name":"Anchor Steam Beer","style":"california-common","notes":"Toasty malt, woody minty hops"},
  {"name":"Anchor Summer Wheat Beer","style":"american-wheat","notes":"Crisp SF wheat, light citrus"},
  {"name":"Anderson Valley Barney Flats Oatmeal Stout","style":"oatmeal-stout","notes":"Roasty, chocolate, creamy oats"},
  {"name":"Anderson Valley Blood Orange Gose","style":"gose","notes":"Blood orange, salt, tart wheat"},
  {"name":"Anderson Valley Boont Amber Ale","style":"american-amber","notes":"Toasted malt, smooth caramel notes"},
  {"name":"Anderson Valley Hop Ottin' IPA","style":"west-coast-ipa","notes":"Citrus, pine, Mendocino classic"},
  {"name":"Anderson Valley The Kimmie The Yink & The Holy Gose","style":"gose","notes":"Tart, salty, lemony with light coriander"},
  {"name":"Asahi Super Dry","style":"american-lager","notes":"Very dry, clean, crisp finish"},
  {"name":"Aslin Master of Karate","style":"neipa","notes":"Tropical, citrus, creamy haze"},
  {"name":"Augustiner Edelstoff","style":"helles","notes":"Elegant, soft malt, refined Munich export"},
  {"name":"Augustiner Lagerbier Hell","style":"helles","notes":"Bready, balanced, crisp Munich classic"},
  {"name":"Avery El Gose","style":"gose","notes":"Tangy, salty, coriander citrus"},
  {"name":"Avery Ellie's Brown Ale","style":"brown-ale","notes":"Chocolate and nutty malt, smooth"},
  {"name":"Avery Salvation","style":"belgian-golden-strong","notes":"Spicy, fruity, warming golden"},
  {"name":"Avery The Reverend","style":"quad","notes":"Cherry, candi sugar, warming strong"},
  {"name":"Avery White Rascal","style":"witbier","notes":"Unfiltered, coriander, orange peel zest"},
  {"name":"Ayinger Altbairisch Dunkel","style":"munich-dunkel","notes":"Toasty, bready, smooth chocolate notes"},
  {"name":"Ayinger Bräuweisse","style":"hefeweizen","notes":"Bright clove, banana, crisp finish"},
  {"name":"Ayinger Celebrator Doppelbock","style":"doppelbock","notes":"Rich dark malt, chocolate, smooth"},
  {"name":"Ayinger Oktoberfest-Märzen","style":"marzen","notes":"Deep malt, toasty, refined"},
  {"name":"Ayinger Ur-Weisse","style":"dunkelweizen","notes":"Amber, banana-clove, bready malt depth"},
  {"name":"Ayinger Weizenbock","style":"weizenbock","notes":"Dark fruit, banana, full-bodied strength"},
  {"name":"Ballast Point Dorado Double IPA","style":"double-ipa","notes":"Citrus, caramel, resinous"},
  {"name":"Ballast Point Even Keel IPA","style":"session-ipa","notes":"Citrus, light body, sessionable"},
  {"name":"Ballast Point Grapefruit Sculpin","style":"west-coast-ipa","notes":"Grapefruit-charged, juicy and bitter"},
  {"name":"Ballast Point Sculpin IPA","style":"west-coast-ipa","notes":"Apricot, peach, lemon, crisp finish"},
  {"name":"Ballast Point Victory at Sea","style":"porter","notes":"Coffee, vanilla, bold imperial porter"},
  {"name":"Barebottle Brewing West Coast IPA","style":"west-coast-ipa","notes":"Dank citrus, SF crowd favorite"},
  {"name":"Bass Pale Ale","style":"english-pale","notes":"Classic English malt, light bitterness"},
  {"name":"Beamish Irish Stout","style":"irish-stout","notes":"Creamy, roasty, dry finish"},
  {"name":"Bear Republic Racer 5 IPA","style":"west-coast-ipa","notes":"Floral citrus, pine, malt backbone"},
  {"name":"Belhaven Scottish Ale","style":"scottish","notes":"Malty caramel, smooth and toasty"},
  {"name":"Bell's Amber Ale","style":"american-amber","notes":"Caramel malt, light citrus hops"},
  {"name":"Bell's Best Brown Ale","style":"brown-ale","notes":"Toasted nutty malt, caramel sweetness"},
  {"name":"Bell's Black Note Stout","style":"imperial-stout","notes":"Bourbon barrel, chocolate, oak, vanilla"},
  {"name":"Bell's Expedition Stout","style":"imperial-stout","notes":"Dark fruit, chocolate, intense roast"},
  {"name":"Bell's Hopslam","style":"double-ipa","notes":"Grapefruit, honey, big hops"},
  {"name":"Bell's Lager of the Lakes","style":"helles","notes":"Crisp, clean, soft Michigan lager"},
  {"name":"Bell's Light Hearted Ale","style":"session-ipa","notes":"Two Hearted's lighter citrus session"},
  {"name":"Bell's Oarsman Ale","style":"berliner","notes":"Mildly tart, sessionable wheat"},
  {"name":"Bell's Oberon Ale","style":"american-wheat","notes":"Citrusy, spicy summer wheat icon"},
  {"name":"Bell's Two Hearted Ale","style":"west-coast-ipa","notes":"All-Centennial grapefruit and pine"},
  {"name":"Bell's Winter White Ale","style":"witbier","notes":"Spiced wheat, clove, seasonal favorite"},
  {"name":"Bierstadt Slow Pour Pils","style":"czech-pilsner","notes":"Creamy foam, decoction malt, refined"},
  {"name":"Birra Moretti","style":"euro-pale-lager","notes":"Balanced Italian lager, gentle hop"},
  {"name":"Birrificio Italiano Tipopils","style":"italian-pilsner","notes":"Dry-hopped, floral, aromatic, dry"},
  {"name":"Bissell Brothers Substance","style":"neipa","notes":"Grapefruit, mango, hazy"},
  {"name":"Bitburger Premium Pils","style":"german-pilsner","notes":"Dry, firm bitterness, crisp"},
  {"name":"Blue Moon Belgian White","style":"witbier","notes":"Orange-garnished, coriander, smooth wheat"},
  {"name":"Boddingtons Pub Ale","style":"english-pale","notes":"Creamy, smooth, gentle malt"},
  {"name":"Boon Kriek","style":"fruited-sour","notes":"Whole cherry lambic, balanced tartness"},
  {"name":"Boon Oude Geuze","style":"lambic","notes":"Balanced lemony funk, lively effervescence"},
  {"name":"Bottle Logic Recursion","style":"double-ipa","notes":"Tropical, juicy, lush double"},
  {"name":"Boulevard Tank 7","style":"saison","notes":"Bright, grapefruit, peppery dry finish"},
  {"name":"Boulevard The Sixth Glass","style":"quad","notes":"Plum, caramel, warming dark"},
  {"name":"Boulevard Unfiltered Wheat Beer","style":"american-wheat","notes":"Bright, lemony, hazy Midwest staple"},
  {"name":"Brooklyn Black Chocolate Stout","style":"imperial-stout","notes":"Bittersweet chocolate, roasty, warming"},
  {"name":"Brooklyn Brown Ale","style":"brown-ale","notes":"Deep malt, chocolate and caramel"},
  {"name":"Brooklyn Lager","style":"vienna-lager","notes":"Amber, toasty, dry-hopped finish"},
  {"name":"Brooklyn Sorachi Ace","style":"saison","notes":"Lemongrass hop, dry golden farmhouse"},
  {"name":"Bud Light","style":"american-lager","notes":"Light-bodied, clean, mild grain"},
  {"name":"Budweiser","style":"american-lager","notes":"Crisp, bready, classic American macro"},
  {"name":"Burlington Beer It's Complicated Being a Wizard","style":"neipa","notes":"Tropical, juicy, hazy"},
  {"name":"Caledonian 80 Shilling","style":"scottish","notes":"Rich malt, gentle hop balance"},
  {"name":"Cantillon Gueuze","style":"lambic","notes":"Intense barnyard funk, bone-dry tartness"},
  {"name":"Carlsberg","style":"euro-pale-lager","notes":"Crisp Danish pilsner, clean malt"},
  {"name":"Cascade Apricot Ale","style":"fruited-sour","notes":"Barrel-aged apricot, juicy tart"},
  {"name":"Cascade Kriek Ale","style":"fruited-sour","notes":"Barrel-aged cherry, intense sour"},
  {"name":"Cellarmaker Dobis","style":"neipa","notes":"Dank tropical, hazy, smooth"},
  {"name":"Chimay Blue (Grande Réserve)","style":"quad","notes":"Dark fruit, spice, warming Trappist"},
  {"name":"Chimay Gold (Dorée)","style":"belgian-blonde","notes":"Light, fruity, peppery Trappist refresher"},
  {"name":"Chimay Red (Première)","style":"dubbel","notes":"Copper, caramel, dried fruit Trappist"},
  {"name":"Chimay White (Cinq Cents)","style":"tripel","notes":"Citrus, spice, dry Trappist"},
  {"name":"Chuckanut Pilsner","style":"czech-pilsner","notes":"Award-winning, clean, floral hops"},
  {"name":"Cigar City Guayabera Citra Pale Ale","style":"session-ipa","notes":"Citra citrus, light sessionable"},
  {"name":"Cigar City Hunahpu's Imperial Stout","style":"imperial-stout","notes":"Chocolate, chili, cinnamon, vanilla"},
  {"name":"Cigar City Jai Alai IPA","style":"west-coast-ipa","notes":"Orange, candied citrus, smooth"},
  {"name":"Cigar City Maduro Brown Ale","style":"brown-ale","notes":"Oatmeal-smooth, cocoa and toffee"},
  {"name":"Cohesion Czech-Style Pale Lager","style":"czech-pilsner","notes":"Side-pull pour, soft, rounded"},
  {"name":"Coors Banquet","style":"american-lager","notes":"Smooth golden lager, slightly sweet"},
  {"name":"Coors Light","style":"american-lager","notes":"Crisp, cold, very light body"},
  {"name":"Corona Extra","style":"american-lager","notes":"Light, citrusy, lime-friendly"},
  {"name":"Corona Premier","style":"american-lager","notes":"Lighter, crisp, low-cal Mexican lager"},
  {"name":"Coronado Weekend Vibes IPA","style":"west-coast-ipa","notes":"Tropical citrus, San Diego hops"},
  {"name":"Corsendonk Pater","style":"dubbel","notes":"Roasted malt, dark fruit, chocolate"},
  {"name":"Crooked Stave Pina Agave","style":"fruited-sour","notes":"Pineapple, agave, bright tartness"},
  {"name":"Crooked Stave Surette","style":"fruited-sour","notes":"Provision saison, tart, lemony funk"},
  {"name":"Curious Traveler Grapefruit Shandy","style":"radler","notes":"Zesty grapefruit, light wheat shandy"},
  {"name":"Cuvée des Jacobins Rouge","style":"flanders-red","notes":"All-oak-aged, sharp tart funk"},
  {"name":"Czechvar Premium Lager","style":"czech-pilsner","notes":"Soft malt, floral Saaz, smooth"},
  {"name":"DAB Original","style":"dortmunder","notes":"Crisp, balanced export lager"},
  {"name":"Delirium Tremens","style":"belgian-golden-strong","notes":"Fruity, spicy, smooth strong golden"},
  {"name":"Deschutes Black Butte Porter","style":"porter","notes":"Creamy chocolate, coffee, balanced roast"},
  {"name":"Deschutes Fresh Squeezed IPA","style":"west-coast-ipa","notes":"Juicy citrus from Citra, Mosaic"},
  {"name":"Deschutes Mirror Pond Pale Ale","style":"american-pale","notes":"Floral Cascade, clean malt finish"},
  {"name":"Deschutes The Abyss","style":"imperial-stout","notes":"Molasses, licorice, barrel complexity"},
  {"name":"Devils Backbone Danzig","style":"baltic-porter","notes":"Roasty, dark fruit, clean finish"},
  {"name":"Devils Backbone Schwartz Bier","style":"schwarzbier","notes":"Dark, dry, gentle roast"},
  {"name":"Devils Backbone Vienna Lager","style":"vienna-lager","notes":"Toasty amber malt, clean"},
  {"name":"Dogfish Head 60 Minute IPA","style":"west-coast-ipa","notes":"Continually hopped, citrus, balanced bitterness"},
  {"name":"Dogfish Head 90 Minute IPA","style":"double-ipa","notes":"Caramel malt, citrus, boozy, bitter"},
  {"name":"Dogfish Head Festina Pêche","style":"berliner","notes":"Light peach tartness, refreshing and dry"},
  {"name":"Dogfish Head Indian Brown Ale","style":"brown-ale","notes":"Caramel, chocolate, hoppy brown"},
  {"name":"Dogfish Head SeaQuench Ale","style":"gose","notes":"Lime, black limes, sea salt, sessionable"},
  {"name":"Dos Equis Amber","style":"vienna-lager","notes":"Light amber, mild toasted malt"},
  {"name":"Dos Equis Lager Especial","style":"american-lager","notes":"Pale, crisp, mellow grain"},
  {"name":"Drake's Aroma Coma IPA","style":"session-ipa","notes":"Citrus, aromatic, East Bay sessionable"},
  {"name":"Drie Fonteinen Oude Kriek","style":"lambic","notes":"Whole-cherry spontaneous tartness"},
  {"name":"Duchesse de Bourgogne","style":"flanders-red","notes":"Sweet-sour, balsamic, cherry chocolate"},
  {"name":"Duck-Rabbit Milk Stout","style":"milk-stout","notes":"Sweet, roasty, creamy body"},
  {"name":"Duvel","style":"belgian-golden-strong","notes":"Crisp, hoppy, dry effervescent benchmark"},
  {"name":"Einbecker Mai-Ur-Bock","style":"maibock","notes":"Pale bock, malty, warming"},
  {"name":"Einbecker Ur-Bock Dunkel","style":"bock","notes":"Malty dark bock, toasty, smooth"},
  {"name":"Equilibrium MC2","style":"double-ipa","notes":"Citrus, tropical, lush double"},
  {"name":"Equilibrium Photon","style":"neipa","notes":"Citrus, stone fruit, hazy"},
  {"name":"Erdinger Pikantus","style":"weizenbock","notes":"Strong dark wheat, malty, banana"},
  {"name":"Erdinger Weissbier","style":"hefeweizen","notes":"Light banana, gentle spice, widely poured"},
  {"name":"Erdinger Weissbier Dunkel","style":"dunkelweizen","notes":"Dark wheat, caramel, gentle banana"},
  {"name":"Estrella Damm","style":"euro-pale-lager","notes":"Smooth Spanish lager, light malt"},
  {"name":"Estrella Jalisco","style":"american-lager","notes":"Crisp Mexican lager, light and clean"},
  {"name":"Faction Pale Ale","style":"west-coast-ipa","notes":"Bright citrus, dry Alameda hops"},
  {"name":"Fantôme Saison","style":"saison","notes":"Funky, herbal, complex farmhouse"},
  {"name":"Fiddlehead IPA","style":"neipa","notes":"Citrus, floral, smooth"},
  {"name":"Fieldwork Brewing West Coast IPA","style":"west-coast-ipa","notes":"Crisp citrus, piney Berkeley flagship"},
  {"name":"Fieldwork Pulp","style":"neipa","notes":"Juicy, soft, citrus-forward"},
  {"name":"Finback Citra Project","style":"neipa","notes":"Bright Citra, tropical haze"},
  {"name":"Finback Double Sesh","style":"double-ipa","notes":"Juicy, tropical, hazy double"},
  {"name":"Finback IPA","style":"west-coast-ipa","notes":"Classic C-hops, Queens flagship"},
  {"name":"Firestone Walker 805 Blonde Ale","style":"blonde","notes":"Smooth malt, light and crisp"},
  {"name":"Firestone Walker Double Jack","style":"double-ipa","notes":"Tangerine, pine, dry finish"},
  {"name":"Firestone Walker Easy Jack IPA","style":"session-ipa","notes":"Tropical citrus, low-ABV crusher"},
  {"name":"Firestone Walker Luponic Distortion","style":"west-coast-ipa","notes":"Rotating hop blends, citrus-forward"},
  {"name":"Firestone Walker Mind Haze","style":"neipa","notes":"Mango, papaya, smooth"},
  {"name":"Firestone Walker Pivo Pils","style":"german-pilsner","notes":"Dry-hopped, floral, snappy finish"},
  {"name":"Firestone Walker Sucaba","style":"american-barleywine","notes":"Bourbon barrel, toffee, vanilla, oak"},
  {"name":"Firestone Walker Union Jack IPA","style":"west-coast-ipa","notes":"Bold citrus, resinous, dry bitterness"},
  {"name":"Firestone Walker Velvet Merlin","style":"oatmeal-stout","notes":"Smooth, chocolate, roasted oats"},
  {"name":"Foam Brewers Built to Spill","style":"neipa","notes":"Bright citrus, tropical, hazy"},
  {"name":"Fort Point KSA","style":"kolsch","notes":"Crisp golden, bright and clean"},
  {"name":"Fort Point Villager IPA","style":"west-coast-ipa","notes":"Balanced citrus, approachable SF IPA"},
  {"name":"Fort Point Westfalia","style":"american-amber","notes":"Nutty red ale, toasty malt"},
  {"name":"Founders All Day IPA","style":"session-ipa","notes":"Citrus, easy-drinking 4.7% sessionable"},
  {"name":"Founders Backwoods Bastard","style":"wee-heavy","notes":"Bourbon barrel, caramel, vanilla, oak"},
  {"name":"Founders Breakfast Stout","style":"imperial-stout","notes":"Coffee, chocolate, oatmeal richness"},
  {"name":"Founders CBS","style":"imperial-stout","notes":"Maple, coffee, bourbon barrel richness"},
  {"name":"Founders Centennial IPA","style":"west-coast-ipa","notes":"Floral, grapefruit, malty backbone"},
  {"name":"Founders Dirty Bastard","style":"wee-heavy","notes":"Caramel, smoky, malty Scotch ale"},
  {"name":"Founders KBS","style":"imperial-stout","notes":"Bourbon barrel, coffee, chocolate, decadent"},
  {"name":"Founders Pale Ale","style":"american-pale","notes":"Balanced citrus hops, smooth caramel"},
  {"name":"Founders Porter","style":"porter","notes":"Rich chocolate, roasty, smooth caramel finish"},
  {"name":"Franziskaner Hefe-Weissbier","style":"hefeweizen","notes":"Smooth banana-clove, bready Munich staple"},
  {"name":"Franziskaner Hefe-Weissbier Dunkel","style":"dunkelweizen","notes":"Toasty, banana, smooth dark Munich wheat"},
  {"name":"Freigeist Abraxxxas","style":"berliner","notes":"Smoky, tart, wheat-driven"},
  {"name":"Früh Kölsch","style":"kolsch","notes":"Smooth, light, delicate Cologne classic"},
  {"name":"Full Sail Amber","style":"american-amber","notes":"Smooth caramel malt, balanced hops"},
  {"name":"Fuller's ESB","style":"english-pale","notes":"Rich caramel, earthy English hops"},
  {"name":"Fuller's London Porter","style":"porter","notes":"Chocolate, coffee, nutty English malt"},
  {"name":"Fuller's London Pride","style":"english-pale","notes":"Malty, biscuit and marmalade notes"},
  {"name":"Funkwerks Saison","style":"saison","notes":"Passionfruit, pepper, crisp dry finish"},
  {"name":"Gaffel Kölsch","style":"kolsch","notes":"Crisp, slightly fruity, dry finish"},
  {"name":"Genesee Bock","style":"bock","notes":"Amber, malty, smooth seasonal"},
  {"name":"Genesee Cream Ale","style":"cream-ale","notes":"Smooth, sweet, lightly creamy classic"},
  {"name":"Ghostfish Grapefruit IPA","style":"west-coast-ipa","notes":"Citrus, gluten-free West Coast"},
  {"name":"Girardin Gueuze 1882 Black Label","style":"lambic","notes":"Unfiltered, dry, rustic funk"},
  {"name":"Golden Road Wolf Pup IPA","style":"west-coast-ipa","notes":"Citrus, light, LA-friendly hops"},
  {"name":"Goose Island 312 Urban Wheat Ale","style":"american-wheat","notes":"Crisp, citrusy, light Chicago wheat"},
  {"name":"Goose Island Bourbon County Stout","style":"imperial-stout","notes":"Bourbon, vanilla, chocolate, oak"},
  {"name":"Goose Island IPA","style":"west-coast-ipa","notes":"Floral, citrus, crisp English-leaning IPA"},
  {"name":"Goose Island Sofie","style":"saison","notes":"Peppery, citrus, vanilla oak tartness"},
  {"name":"Great Divide Hercules Double IPA","style":"double-ipa","notes":"Pine, grapefruit, resinous"},
  {"name":"Great Divide Old Ruffian Barleywine","style":"american-barleywine","notes":"Caramel, hoppy, rich malt"},
  {"name":"Great Lakes Blackout Stout","style":"imperial-stout","notes":"Roasty, chocolate, boozy depth"},
  {"name":"Great Lakes Burning River Pale Ale","style":"american-pale","notes":"Crisp citrus hops, firm bitterness"},
  {"name":"Great Lakes Conway's Irish Ale","style":"irish-red","notes":"Toasty malt, smooth caramel body"},
  {"name":"Great Lakes Dortmunder Gold","style":"dortmunder","notes":"Balanced malt-hop, smooth, golden"},
  {"name":"Great Lakes Edmund Fitzgerald Porter","style":"porter","notes":"Bittersweet chocolate, espresso, robust"},
  {"name":"Great Lakes Eliot Ness","style":"vienna-lager","notes":"Rich toasty malt, smooth"},
  {"name":"Great Lakes Oktoberfest","style":"marzen","notes":"Rich malt, balanced, festive"},
  {"name":"Green Cheek West Coast Double IPA","style":"double-ipa","notes":"Citrus, pine, crisp, dry"},
  {"name":"Green Flash West Coast IPA","style":"west-coast-ipa","notes":"Dank, piney, firm bitterness"},
  {"name":"Grimbergen Blonde","style":"belgian-blonde","notes":"Golden, malty, subtly spiced"},
  {"name":"Grimm Double Negative","style":"imperial-stout","notes":"Roasty, chocolate, smooth NYC stout"},
  {"name":"Grimm Tesseract","style":"double-ipa","notes":"Dank, tropical, lush double"},
  {"name":"Grolsch Premium Pilsner","style":"euro-pale-lager","notes":"Crisp Dutch lager, slight hop bite"},
  {"name":"Guinness Draught","style":"irish-stout","notes":"Creamy, roasty, light coffee dryness"},
  {"name":"Guinness Extra Stout","style":"irish-stout","notes":"Sharper roast, bitter, fuller body"},
  {"name":"Guinness Nitro Cold Brew Coffee","style":"nitro-stout","notes":"Cold brew coffee, creamy, roasty"},
  {"name":"Gulden Draak","style":"quad","notes":"Dark, malty, caramel, strong"},
  {"name":"Hacker-Pschorr Dunkel","style":"munich-dunkel","notes":"Smooth, malty, gently roasted"},
  {"name":"Hacker-Pschorr Munich Gold","style":"helles","notes":"Golden, bready, gently hopped"},
  {"name":"Hacker-Pschorr Weisse","style":"hefeweizen","notes":"Honeyed banana, soft clove, Munich tradition"},
  {"name":"Half Acre Daisy Cutter Pale Ale","style":"american-pale","notes":"Bright citrus, dank Chicago favorite"},
  {"name":"Harpoon UFO Big Squeeze Shandy","style":"fruit-wheat","notes":"Grapefruit-forward, bright, citrusy wheat"},
  {"name":"Harpoon UFO White","style":"american-wheat","notes":"Unfiltered, smooth, lightly spiced wheat"},
  {"name":"Headlands Point Bonita IPA","style":"west-coast-ipa","notes":"Citrus-forward, clean Marin IPA"},
  {"name":"Heater Allen Pils","style":"czech-pilsner","notes":"Crisp, delicate, balanced Saaz"},
  {"name":"Heineken","style":"euro-pale-lager","notes":"Crisp Dutch lager, mild skunky hop"},
  {"name":"HenHouse Big Chief Pale Ale","style":"american-pale","notes":"Sonoma citrus-hop, sessionable and bright"},
  {"name":"HenHouse IPA","style":"west-coast-ipa","notes":"Citrus, pine, crisp Sonoma hops"},
  {"name":"Hill Farmstead Double Citra","style":"double-ipa","notes":"Citrus, tropical, soft double"},
  {"name":"Hoegaarden Original White Ale","style":"witbier","notes":"Coriander, orange peel, hazy Belgian classic"},
  {"name":"Hofbräu Maibock","style":"maibock","notes":"Strong golden, malty, smooth"},
  {"name":"Hofbräu Oktoberfest","style":"marzen","notes":"Golden, malty, smooth strength"},
  {"name":"Hofbräu Original","style":"helles","notes":"Light bready malt, smooth and easy"},
  {"name":"Industrial Arts Wrench","style":"neipa","notes":"Juicy, citrus, soft bitterness"},
  {"name":"Industrial Arts Wrench IPA","style":"west-coast-ipa","notes":"Citrus, pine, Hudson Valley flagship"},
  {"name":"Interboro Carrie Nation IPA","style":"west-coast-ipa","notes":"Citrus, pine, Brooklyn IPA"},
  {"name":"Interboro Surrounded By Idiots","style":"neipa","notes":"Citrus, tropical, smooth haze"},
  {"name":"Jack's Abby House Lager","style":"helles","notes":"Crisp, soft, sessionable craft lager"},
  {"name":"Jack's Abby Post Shift Pilsner","style":"german-pilsner","notes":"Light, balanced, easy session pilsner"},
  {"name":"Jester King Atrial Rubicite","style":"fruited-sour","notes":"Raspberry farmhouse, vibrant tart funk"},
  {"name":"Jever Pilsener","style":"german-pilsner","notes":"Assertively bitter, dry, herbal"},
  {"name":"Jolly Pumpkin La Roja","style":"fruited-sour","notes":"Oak-aged amber, sour cherry funk"},
  {"name":"Karl Strauss Tower 10 IPA","style":"west-coast-ipa","notes":"Citrus, floral, balanced San Diego IPA"},
  {"name":"KCBC The Squad","style":"neipa","notes":"Juicy, soft, tropical"},
  {"name":"Killian's Irish Red","style":"irish-red","notes":"Caramel malt, mildly sweet finish"},
  {"name":"Kirin Ichiban","style":"american-lager","notes":"Smooth, malty, all-malt Japanese lager"},
  {"name":"Knee Deep Simtra IPA","style":"west-coast-ipa","notes":"Simcoe, citrus, resinous bitterness"},
  {"name":"Kona Big Wave Golden Ale","style":"blonde","notes":"Light tropical, smooth easy-drinking"},
  {"name":"König Ludwig Dunkel","style":"munich-dunkel","notes":"Toasty, malty, smooth finish"},
  {"name":"König Pilsener","style":"german-pilsner","notes":"Crisp, clean, balanced bitterness"},
  {"name":"Köstritzer Schwarzbier","style":"schwarzbier","notes":"Dark, smooth, light roast, crisp"},
  {"name":"La Chouffe","style":"belgian-golden-strong","notes":"Coriander, fruity, peppery golden"},
  {"name":"La Fin du Monde","style":"tripel","notes":"Spicy, fruity, effervescent Quebec classic"},
  {"name":"La Trappe Blond","style":"belgian-blonde","notes":"Soft malt, fruity Trappist easy-drinker"},
  {"name":"La Trappe Dubbel","style":"dubbel","notes":"Caramel, banana, smooth Trappist"},
  {"name":"La Trappe Quadrupel","style":"quad","notes":"Caramel, raisin, warming malty"},
  {"name":"Lagunitas A Little Sumpin' Sumpin' Ale","style":"american-wheat","notes":"Hoppy wheat, citrus, smooth body"},
  {"name":"Lagunitas Censored Rich Copper Ale","style":"american-amber","notes":"Malty caramel, balanced hop bitterness"},
  {"name":"Lagunitas DayTime IPA","style":"session-ipa","notes":"Light citrus, crisp, low-cal"},
  {"name":"Lagunitas Hop Stoopid","style":"double-ipa","notes":"Citrus, pine, bitter punch"},
  {"name":"Lagunitas IPA","style":"west-coast-ipa","notes":"Caramel malt, bright citrus hops"},
  {"name":"Lagunitas Maximus IPA","style":"west-coast-ipa","notes":"Bigger citrus, resinous bitterness"},
  {"name":"Lagunitas New Dogtown Pale Ale","style":"american-pale","notes":"Resinous hops, citrus and caramel"},
  {"name":"Lagunitas Olde GnarlyWine","style":"american-barleywine","notes":"Caramel, hoppy, warming malt"},
  {"name":"Lagunitas Pils","style":"czech-pilsner","notes":"Crisp, spicy hops, dry finish"},
  {"name":"Lagunitas Sucks","style":"west-coast-ipa","notes":"Bright citrus, juicy, dry finish"},
  {"name":"Lancaster Milk Stout","style":"milk-stout","notes":"Coffee, milk chocolate, subtle sweetness"},
  {"name":"Laughing Monk Brewing IPA","style":"west-coast-ipa","notes":"Citrus, pine, SF taproom staple"},
  {"name":"Lawson's Finest Double Sunshine","style":"double-ipa","notes":"Bright citrus, tropical, lush"},
  {"name":"Lawson's Finest Sip of Sunshine","style":"double-ipa","notes":"Tropical, citrus, smooth, juicy"},
  {"name":"Leffe Blonde","style":"belgian-blonde","notes":"Smooth, lightly spiced, honeyed malt"},
  {"name":"Left Hand Milk Stout","style":"milk-stout","notes":"Sweet, creamy, chocolate, coffee"},
  {"name":"Left Hand Milk Stout Nitro","style":"nitro-stout","notes":"Creamy, chocolate, smooth cascade"},
  {"name":"Leinenkugel's Berry Weiss","style":"fruit-wheat","notes":"Mixed berries, sweet, fruity wheat"},
  {"name":"Leinenkugel's Summer Shandy","style":"radler","notes":"Lemonade-wheat blend, bright and crisp"},
  {"name":"Liefmans Goudenband","style":"flanders-red","notes":"Oud bruin, sweet-sour, fruity"},
  {"name":"Lindemans Cassis","style":"fruited-sour","notes":"Blackcurrant lambic, tart-sweet"},
  {"name":"Lindemans Cuvée René","style":"lambic","notes":"Classic oak gueuze, dry funky tartness"},
  {"name":"Lindemans Framboise","style":"fruited-sour","notes":"Sweet raspberry lambic, jammy"},
  {"name":"Lindemans Kriek","style":"fruited-sour","notes":"Sweet cherry lambic, fruity"},
  {"name":"Lindemans Pêche","style":"fruited-sour","notes":"Sweet peach lambic, juicy"},
  {"name":"Little Kings Cream Ale","style":"cream-ale","notes":"Smooth, malty, mini-bottle cult classic"},
  {"name":"Live Oak Hefeweizen","style":"hefeweizen","notes":"Austin classic, decoction banana-clove depth"},
  {"name":"Live Oak Pilz","style":"czech-pilsner","notes":"Decoction malt, soft, spicy hops"},
  {"name":"Local Brewing Co IPA","style":"west-coast-ipa","notes":"Crisp citrus, SoMa SF brewery"},
  {"name":"Lone Star","style":"american-lager","notes":"Light Texan lager, corn-sweet, easy"},
  {"name":"Long Trail Ale","style":"altbier","notes":"Vermont altbier, smooth malty body"},
  {"name":"Lord Hobo Boom Sauce","style":"neipa","notes":"Citrus, tropical, smooth"},
  {"name":"Lost Coast Indica IPA","style":"west-coast-ipa","notes":"Citrus, floral, Humboldt staple"},
  {"name":"Mahou Cinco Estrellas","style":"euro-pale-lager","notes":"Crisp Spanish lager, mild sweetness"},
  {"name":"Maine Beer Company King Titus","style":"porter","notes":"Robust chocolate, roasty, full body"},
  {"name":"Maine Beer Dinner","style":"double-ipa","notes":"Intense citrus, pine, lush"},
  {"name":"Maine Beer Lunch","style":"neipa","notes":"Pine, citrus, balanced"},
  {"name":"Metropolitan Krankshaft Kölsch","style":"kolsch","notes":"Crisp, clean Chicago German-style"},
  {"name":"Miller High Life","style":"american-lager","notes":"Crisp, corn-sweet, the champagne of beers"},
  {"name":"Miller Lite","style":"american-lager","notes":"Light, dry, faintly hoppy"},
  {"name":"Modelo Especial","style":"american-lager","notes":"Crisp Mexican lager, light orange note"},
  {"name":"Modelo Oro","style":"american-lager","notes":"Light, crisp, smooth low-carb Mexican lager"},
  {"name":"Modern Times Black House","style":"imperial-stout","notes":"Coffee-forward, roasty, smooth"},
  {"name":"Modern Times Fortunate Islands","style":"american-wheat","notes":"Citrus, tropical, hoppy wheat"},
  {"name":"Modern Times Orderville","style":"neipa","notes":"Mosaic, juicy, tropical haze"},
  {"name":"Monkish Foggy Window","style":"neipa","notes":"Soft, juicy, tropical"},
  {"name":"Monkish Le IPA","style":"neipa","notes":"Citrus, tropical, creamy haze"},
  {"name":"Monkish Moonk","style":"double-ipa","notes":"Triple hazy, tropical, lush"},
  {"name":"Murphy's Irish Stout","style":"irish-stout","notes":"Smooth, mild, gentle roast"},
  {"name":"Narragansett Lager","style":"american-lager","notes":"Crisp New England macro, bready malt"},
  {"name":"Negra Modelo","style":"munich-dunkel","notes":"Smooth dark lager, light caramel"},
  {"name":"New Belgium Fat Tire Amber Ale","style":"american-amber","notes":"Toasty biscuit malt, balanced finish"},
  {"name":"New Belgium La Folie","style":"flanders-red","notes":"Sour brown, green apple, tart"},
  {"name":"New Belgium Voodoo Ranger Imperial IPA","style":"double-ipa","notes":"Citrus, pine, bold hops"},
  {"name":"New Belgium Voodoo Ranger Juicy Haze","style":"neipa","notes":"Pineapple, tangerine, juicy"},
  {"name":"New Glarus Raspberry Tart","style":"fruited-sour","notes":"Intense raspberry, tart and jammy"},
  {"name":"New Glarus Spotted Cow","style":"cream-ale","notes":"Fruity, smooth Wisconsin farmhouse cream ale"},
  {"name":"New Glarus Wisconsin Belgian Red","style":"fruited-sour","notes":"Whole Door County cherries, rich tart"},
  {"name":"New Holland The Poet Oatmeal Stout","style":"oatmeal-stout","notes":"Coffee, chocolate, silky body"},
  {"name":"Newcastle Brown Ale","style":"brown-ale","notes":"Nutty caramel, smooth light body"},
  {"name":"Night Shift The 87","style":"neipa","notes":"Juicy, citrus, soft"},
  {"name":"North Coast Acme IPA","style":"west-coast-ipa","notes":"Citrus, balanced, NorCal classic"},
  {"name":"North Coast Brother Thelonious","style":"dubbel","notes":"Rich dark fruit, chocolate, strong"},
  {"name":"North Coast Le Merle","style":"saison","notes":"Fruity, tart, peppery farmhouse"},
  {"name":"North Coast Old Rasputin","style":"imperial-stout","notes":"Intense roast, chocolate, boozy warmth"},
  {"name":"North Coast PranQster","style":"belgian-golden-strong","notes":"Floral, fruity, smooth golden"},
  {"name":"North Coast Red Seal Ale","style":"american-amber","notes":"Rich malt, robust hop character"},
  {"name":"Notch Session Pils","style":"czech-pilsner","notes":"Low-ABV, crackery, Saaz-driven"},
  {"name":"O'Hara's Irish Stout","style":"irish-stout","notes":"Roasted coffee, dry, full-flavored"},
  {"name":"Odell 5 Barrel Pale Ale","style":"american-pale","notes":"Floral, citrus and stone fruit"},
  {"name":"Odell 90 Shilling Ale","style":"scottish","notes":"Light caramel malt, smooth balance"},
  {"name":"Off Color Troublesome","style":"gose","notes":"Wheat-forward, tart, gently salty"},
  {"name":"Old Speckled Hen","style":"english-pale","notes":"Toffee malt, fruity and smooth"},
  {"name":"Ommegang Abbey Ale","style":"dubbel","notes":"Plum, chocolate, warming malt"},
  {"name":"Ommegang Gnomegang","style":"belgian-golden-strong","notes":"Peppery, fruity, dry collaboration golden"},
  {"name":"Ommegang Hennepin","style":"saison","notes":"Spicy, orange peel, dry effervescent"},
  {"name":"Ommegang Three Philosophers","style":"quad","notes":"Cherry, chocolate, rich kriek blend"},
  {"name":"Ommegang Witte","style":"witbier","notes":"Bright orange, coriander, refreshing Belgian-style"},
  {"name":"Orkney Skull Splitter","style":"wee-heavy","notes":"Dried fruit, caramel, warming"},
  {"name":"Oskar Blues Dale's Pale Ale","style":"american-pale","notes":"Hoppy, citrus and pine, canned classic"},
  {"name":"Oskar Blues IPA","style":"west-coast-ipa","notes":"Citrus, pine, sturdy bitterness"},
  {"name":"Oskar Blues Old Chub","style":"wee-heavy","notes":"Caramel, cocoa, smoky malt"},
  {"name":"Oskar Blues Pinner Throwback IPA","style":"session-ipa","notes":"Tropical citrus, light and crushable"},
  {"name":"Oskar Blues Ten Fidy","style":"imperial-stout","notes":"Viscous, chocolate, caramel, espresso"},
  {"name":"Other Half All Citra Everything","style":"neipa","notes":"Pure Citra, grapefruit, juicy"},
  {"name":"Other Half Double Dry Hopped Double Mosaic Dream","style":"double-ipa","notes":"Mosaic, tropical, juicy double"},
  {"name":"Other Half Forever Ever","style":"double-ipa","notes":"Citra-driven, juicy, dank double"},
  {"name":"Other Half Green City","style":"neipa","notes":"Soft, dank, tropical haze"},
  {"name":"Other Half Green Diamond IPA","style":"west-coast-ipa","notes":"Crisp, dank West Coast Brooklyn"},
  {"name":"Other Half Snowbirds","style":"imperial-stout","notes":"Coconut, cacao, almond, bourbon barrel"},
  {"name":"Pabst Blue Ribbon","style":"american-lager","notes":"Easy-drinking, mild malt, dive-bar staple"},
  {"name":"Pacifico","style":"american-lager","notes":"Clean Mexican pilsner-style, easy finish"},
  {"name":"Paulaner Hefe-Weizen Naturtrüb","style":"hefeweizen","notes":"Creamy banana, clove, soft carbonation"},
  {"name":"Paulaner Oktoberfest Märzen","style":"marzen","notes":"Rich toasty malt, smooth, festive"},
  {"name":"Paulaner Premium Lager","style":"helles","notes":"Soft grain, mild floral hops"},
  {"name":"Paulaner Salvator","style":"doppelbock","notes":"Deep malt, dark fruit, warming"},
  {"name":"Pelican Kiwanda Cream Ale","style":"blonde","notes":"Smooth, lightly sweet, easy golden"},
  {"name":"Peroni Nastro Azzurro","style":"euro-pale-lager","notes":"Crisp Italian lager, light and dry"},
  {"name":"Petrus Aged Pale","style":"flanders-red","notes":"Oak-aged, crisp tart, dry"},
  {"name":"Pilsner Urquell","style":"czech-pilsner","notes":"Rich Czech lager, spicy Saaz hops"},
  {"name":"Piraat","style":"belgian-golden-strong","notes":"Bold, fruity, warming strong golden"},
  {"name":"Pizza Port Swami's IPA","style":"west-coast-ipa","notes":"Citrus, pine, classic San Diego"},
  {"name":"Port Brewing Wipeout IPA","style":"west-coast-ipa","notes":"Citrus, pine, crisp bitterness"},
  {"name":"Presidente","style":"american-lager","notes":"Crisp Dominican pilsner, clean finish"},
  {"name":"Professor Fritz Briem 1809 Berliner Weisse","style":"berliner","notes":"Traditional, sharp lactic acidity, wheaty"},
  {"name":"Pyramid Apricot Ale","style":"fruit-wheat","notes":"Juicy apricot, light, refreshing wheat"},
  {"name":"Radeberger Pilsner","style":"german-pilsner","notes":"Refined, dry, lightly hopped"},
  {"name":"Red Stripe","style":"american-lager","notes":"Smooth Jamaican lager, lightly sweet"},
  {"name":"Redhook ESB","style":"english-pale","notes":"Caramel malt, balanced hop finish"},
  {"name":"Reissdorf Kölsch","style":"kolsch","notes":"Classic Cologne, crisp and delicate"},
  {"name":"Revolution Anti-Hero IPA","style":"west-coast-ipa","notes":"Citrus, pine, Chicago flagship"},
  {"name":"Rochefort 10","style":"quad","notes":"Port, fig, chocolate Trappist depth"},
  {"name":"Rochefort 6","style":"dubbel","notes":"Herbal, fruity, balanced Trappist"},
  {"name":"Rodenbach Alexander","style":"fruited-sour","notes":"Flanders red with cherry, balanced sweet-sour"},
  {"name":"Rodenbach Classic","style":"flanders-red","notes":"Light tart, woody, refreshing"},
  {"name":"Rodenbach Grand Cru","style":"flanders-red","notes":"Oak-aged, balsamic, sweet-sour cherry"},
  {"name":"Rogue Dead Guy Ale","style":"maibock","notes":"Malty, honeyed, smooth strength"},
  {"name":"Rogue Hazelnut Brown Nectar","style":"brown-ale","notes":"Rich hazelnut, toasty caramel malt"},
  {"name":"Rogue Shakespeare Oatmeal Stout","style":"oatmeal-stout","notes":"Roasty, bitter chocolate, oat smooth"},
  {"name":"Russian River Blind Pig IPA","style":"west-coast-ipa","notes":"Clean citrus, sharp dry bitterness"},
  {"name":"Russian River Consecration","style":"fruited-sour","notes":"Cabernet barrel, currants, rich sour"},
  {"name":"Russian River Damnation","style":"belgian-golden-strong","notes":"Pear, spice, dry golden strength"},
  {"name":"Russian River Pliny the Elder","style":"double-ipa","notes":"Pine, citrus, resinous, dry"},
  {"name":"Russian River Supplication","style":"fruited-sour","notes":"Pinot barrel, sour cherries, funk"},
  {"name":"Russian River Temptation","style":"fruited-sour","notes":"Chardonnay barrel, bright wine tartness"},
  {"name":"Saint Arnold Fancy Lawnmower","style":"kolsch","notes":"Crisp, light grainy, German-style"},
  {"name":"Saison Dupont","style":"saison","notes":"Dry, peppery, citrusy farmhouse benchmark"},
  {"name":"Sam Adams Black Lager","style":"schwarzbier","notes":"Roasty, light-bodied, smooth"},
  {"name":"Sam Adams Boston Lager","style":"vienna-lager","notes":"Caramel malt, balanced, toasty"},
  {"name":"Sam Adams OctoberFest","style":"marzen","notes":"Caramel malt, smooth, seasonal"},
  {"name":"Sam Adams Summer Ale","style":"american-wheat","notes":"Lemon zest, grains of paradise, crisp"},
  {"name":"Samuel Adams Cherry Wheat","style":"fruit-wheat","notes":"Cherry, honey, smooth wheat ale"},
  {"name":"Samuel Adams Irish Red","style":"irish-red","notes":"Caramel malt, balanced roasty finish"},
  {"name":"Samuel Adams Nitro Coffee Stout","style":"nitro-stout","notes":"Velvety, coffee, roasted malt"},
  {"name":"Samuel Smith's Nut Brown Ale","style":"brown-ale","notes":"Toasty hazelnut malt, dry finish"},
  {"name":"Samuel Smith's Oatmeal Stout","style":"oatmeal-stout","notes":"Silky, chocolate, oat smoothness"},
  {"name":"Samuel Smith's Old Brewery Pale Ale","style":"english-pale","notes":"Nutty malt, balanced earthy hops"},
  {"name":"Samuel Smith's Taddy Porter","style":"porter","notes":"Dark malt, dried fruit, dry finish"},
  {"name":"Sapporo Premium","style":"american-lager","notes":"Crisp, dry Japanese rice lager"},
  {"name":"Schell's Pils","style":"german-pilsner","notes":"Crisp, floral, balanced Minnesota classic"},
  {"name":"Schlafly Kölsch","style":"kolsch","notes":"Crisp, delicate fruit and grain"},
  {"name":"Schlafly Pale Ale","style":"english-pale","notes":"English-style, balanced malt and hops"},
  {"name":"Schneider Weisse Aventinus Tap 6","style":"weizenbock","notes":"Rich, dark, banana, plum, warming"},
  {"name":"Schneider Weisse Original Tap 7","style":"hefeweizen","notes":"Amber, clove-forward, fruity Bavarian classic"},
  {"name":"Schöfferhofer Grapefruit","style":"radler","notes":"Wheat beer, juicy grapefruit, fizzy"},
  {"name":"Sea Dog Blueberry Wheat Ale","style":"fruit-wheat","notes":"Real blueberry, light, crisp Maine wheat"},
  {"name":"Shiner Bock","style":"bock","notes":"Light amber, mild malt, easy"},
  {"name":"Shock Top Raspberry Wheat","style":"fruit-wheat","notes":"Raspberry, smooth Belgian-style wheat"},
  {"name":"Sierra Nevada Bigfoot Barleywine","style":"american-barleywine","notes":"Hoppy, caramel, boozy, intense"},
  {"name":"Sierra Nevada Celebration IPA","style":"west-coast-ipa","notes":"Fresh-hop, piney winter classic"},
  {"name":"Sierra Nevada Hazy Little Thing","style":"neipa","notes":"Juicy, tropical, soft bitterness"},
  {"name":"Sierra Nevada Kellerweis","style":"hefeweizen","notes":"Open-fermented, banana, clove, citrus"},
  {"name":"Sierra Nevada Narwhal Imperial Stout","style":"imperial-stout","notes":"Roasty, dark chocolate, full body"},
  {"name":"Sierra Nevada Nooner Pilsner","style":"german-pilsner","notes":"Crisp, hop-forward, refreshing pils"},
  {"name":"Sierra Nevada Oktoberfest","style":"marzen","notes":"Toasty, crisp, collaboration brew"},
  {"name":"Sierra Nevada Otra Vez","style":"gose","notes":"Prickly pear and grapefruit, crisp salinity"},
  {"name":"Sierra Nevada Pale Ale","style":"american-pale","notes":"Piney Cascade hops, caramel malt backbone"},
  {"name":"Sierra Nevada Porter","style":"porter","notes":"Chocolate, light coffee, clean finish"},
  {"name":"Sierra Nevada Summerfest","style":"german-pilsner","notes":"Crisp, clean, gently hopped"},
  {"name":"Sierra Nevada Torpedo Extra IPA","style":"west-coast-ipa","notes":"Piney, citrusy, dry-hopped classic"},
  {"name":"Sinebrychoff Porter","style":"baltic-porter","notes":"Licorice, dark fruit, rich roast"},
  {"name":"Singha","style":"american-lager","notes":"Crisp Thai lager, slightly hoppy"},
  {"name":"SingleCut Softly Spoken Magic Spells","style":"neipa","notes":"Juicy, tropical, hazy"},
  {"name":"Sixpoint 3Beans","style":"imperial-stout","notes":"Coffee, cocoa, chili porter-stout"},
  {"name":"Sixpoint Bengali IPA","style":"west-coast-ipa","notes":"Orange citrus, piney Brooklyn classic"},
  {"name":"Sixpoint Jammer","style":"gose","notes":"Sour, salty, sessionable wheat"},
  {"name":"Sixpoint Resin","style":"double-ipa","notes":"Sticky pine, citrus, resinous"},
  {"name":"Sixpoint The Crisp","style":"german-pilsner","notes":"Crackery, refreshing, dry"},
  {"name":"Smithwick's Irish Ale","style":"irish-red","notes":"Smooth malty, light caramel sweetness"},
  {"name":"Smuttynose Baltic Porter","style":"baltic-porter","notes":"Dark fruit, chocolate, smooth lager"},
  {"name":"Smuttynose Old Brown Dog Ale","style":"brown-ale","notes":"Nutty caramel malt, smooth body"},
  {"name":"Societe The Pupil IPA","style":"west-coast-ipa","notes":"Citrus, floral, refined San Diego"},
  {"name":"Spaten Oktoberfest","style":"marzen","notes":"Amber, bready malt, balanced"},
  {"name":"Spaten Optimator","style":"doppelbock","notes":"Chocolate malt, full-bodied, smooth"},
  {"name":"Spaten Premium Lager","style":"helles","notes":"Clean malt, subtle sweetness"},
  {"name":"Speakeasy Big Daddy IPA","style":"west-coast-ipa","notes":"Citrus, pine, classic SF IPA"},
  {"name":"Spezial Rauchbier Lager","style":"rauchbier","notes":"Gentle smoke, malty, balanced"},
  {"name":"St. Bernardus Abt 12","style":"quad","notes":"Rich dark fruit, caramel, complex"},
  {"name":"St. Bernardus Extra 4","style":"belgian-blonde","notes":"Crisp, dry, herbal and citrusy"},
  {"name":"St. Bernardus Pater 6","style":"dubbel","notes":"Raisin, caramel, soft malty depth"},
  {"name":"St. Bernardus Tripel","style":"tripel","notes":"Citrus, pepper, smooth golden strength"},
  {"name":"St. Bernardus Wit","style":"witbier","notes":"Soft, spicy, citrusy Pierre Celis recipe"},
  {"name":"Stella Artois","style":"euro-pale-lager","notes":"Crisp Belgian pilsner, faint sweetness"},
  {"name":"Stiegl Radler Grapefruit","style":"radler","notes":"Tart grapefruit, light, refreshing Austrian"},
  {"name":"Stone Delicious IPA","style":"west-coast-ipa","notes":"Lemony citrus, gluten-reduced, crisp"},
  {"name":"Stone Enjoy By IPA","style":"double-ipa","notes":"Fresh citrus, pine, bold"},
  {"name":"Stone Go To IPA","style":"session-ipa","notes":"Hop-bursted citrus, dry session"},
  {"name":"Stone Imperial Russian Stout","style":"imperial-stout","notes":"Bold roast, dark fruit, chocolate"},
  {"name":"Stone IPA","style":"west-coast-ipa","notes":"Aggressive pine and grapefruit bitterness"},
  {"name":"Stone Pale Ale 2.0","style":"american-pale","notes":"Tropical hops, light caramel malt"},
  {"name":"Stone Smoked Porter","style":"porter","notes":"Smoky, chocolate, roasted depth"},
  {"name":"Suarez Family Palatine Pils","style":"czech-pilsner","notes":"Crushable, bright, spicy Saaz"},
  {"name":"Sun King Sunlight Cream Ale","style":"cream-ale","notes":"Crisp, light, smooth Indiana cream ale"},
  {"name":"Surly Bender","style":"brown-ale","notes":"Oatmeal brown, coffee and chocolate"},
  {"name":"Surly Furious","style":"west-coast-ipa","notes":"Grapefruit, pine, caramel malt punch"},
  {"name":"Tecate","style":"american-lager","notes":"Light, crisp, lime and salt friendly"},
  {"name":"Telegraph California Ale","style":"blonde","notes":"Santa Barbara golden, lightly fruity"},
  {"name":"The Alchemist Focal Banger","style":"neipa","notes":"Citrus, pine, clean bitterness"},
  {"name":"The Alchemist Heady Topper","style":"double-ipa","notes":"Juicy, dank, citrus, iconic"},
  {"name":"The Bruery Hottenroth","style":"berliner","notes":"Low ABV, lemony, clean tartness"},
  {"name":"The Bruery Sour in the Rye","style":"fruited-sour","notes":"Rye sour, oak, tart fruit"},
  {"name":"The Bruery Tart of Darkness","style":"fruited-sour","notes":"Sour stout, dark fruit, roast"},
  {"name":"The Rare Barrel Ensorcelled","style":"fruited-sour","notes":"Raspberry golden sour, oak tartness"},
  {"name":"Three Floyds Gumballhead","style":"american-wheat","notes":"Cascade-hopped, citrusy American wheat"},
  {"name":"Three Floyds Zombie Dust","style":"american-pale","notes":"Juicy Citra, grapefruit and tropical fruit"},
  {"name":"Threes Logical Conclusion","style":"neipa","notes":"Soft, juicy, citrus-forward"},
  {"name":"Threes Vliet Pilsner","style":"czech-pilsner","notes":"Crisp, clean Brooklyn-brewed pils"},
  {"name":"Timmermans Oude Gueuze","style":"lambic","notes":"Traditional, tart, earthy"},
  {"name":"Tired Hands HopHands","style":"neipa","notes":"Juicy, citrus, soft bitterness"},
  {"name":"Toppling Goliath King Sue","style":"double-ipa","notes":"Citra, juicy, tropical, dank"},
  {"name":"Toppling Goliath Mornin' Delight","style":"imperial-stout","notes":"Coffee, maple, barrel-aged decadence"},
  {"name":"Toppling Goliath Pseudo Sue","style":"american-pale","notes":"Citra-forward, mango and grapefruit"},
  {"name":"Track 7 Hoppy Palm IPA","style":"west-coast-ipa","notes":"Citrus, pine, Sacramento flagship"},
  {"name":"Tree House Haze","style":"neipa","notes":"Dank tropical, hazy soft finish"},
  {"name":"Tree House Juice Machine","style":"double-ipa","notes":"Mango, citrus, pillowy double"},
  {"name":"Tree House Julius","style":"neipa","notes":"Orange, mango, pillowy mouthfeel"},
  {"name":"Tree House King Julius","style":"double-ipa","notes":"Orange, mango, intense, creamy"},
  {"name":"Tree House Very Green","style":"double-ipa","notes":"Dank, tropical, intensely hopped"},
  {"name":"Trillium Congress Street","style":"neipa","notes":"Galaxy-forward, peachy, tropical"},
  {"name":"Trillium DDH Melcher Street","style":"double-ipa","notes":"Dank, juicy, tropical double"},
  {"name":"Trillium Fort Point","style":"neipa","notes":"Stone fruit, citrus, smooth"},
  {"name":"Tripel Karmeliet","style":"tripel","notes":"Banana, vanilla, creamy three-grain"},
  {"name":"Tröegs HopBack Amber Ale","style":"american-amber","notes":"Fresh hops, toasty malt balance"},
  {"name":"Tröegs Nugget Nectar","style":"american-amber","notes":"Intensely hoppy, citrus and caramel"},
  {"name":"Tröegs Troegenator","style":"doppelbock","notes":"Rich caramel malt, dark fruit"},
  {"name":"Trumer Pils","style":"german-pilsner","notes":"Delicate, light-bodied, fine bitterness"},
  {"name":"Tsingtao","style":"american-lager","notes":"Light Chinese lager, faint hop crispness"},
  {"name":"Two Roads Lil' Heaven IPA","style":"session-ipa","notes":"Tropical citrus, crisp session"},
  {"name":"Uerige Altbier","style":"altbier","notes":"Düsseldorf classic, malty and bitter"},
  {"name":"Unibroue Trois Pistoles","style":"quad","notes":"Plum, port, dark malt richness"},
  {"name":"Upland Dantalion","style":"fruited-sour","notes":"Dark sour, blackberry, oak"},
  {"name":"Victoria","style":"american-lager","notes":"Amber Vienna-leaning Mexican lager, malty"},
  {"name":"Victory DirtWolf","style":"double-ipa","notes":"Citrus, pine, dank, dry"},
  {"name":"Victory Golden Monkey","style":"tripel","notes":"Fruity, spicy, warming golden"},
  {"name":"Victory Helles Lager","style":"helles","notes":"Crisp, honeyed grain, clean"},
  {"name":"Victory Old Horizontal","style":"american-barleywine","notes":"Caramel, fruity, balanced bitterness"},
  {"name":"Victory Prima Pils","style":"german-pilsner","notes":"Hop-forward, spicy, bracing finish"},
  {"name":"Victory Storm King Imperial Stout","style":"imperial-stout","notes":"Hoppy, roasty, dark chocolate"},
  {"name":"Victory Summer Love Ale","style":"blonde","notes":"Bright, light hops, crisp golden"},
  {"name":"von Trapp Pilsner","style":"czech-pilsner","notes":"Soft, floral, Vermont Czech-style pils"},
  {"name":"Warsteiner Premium Pilsener","style":"german-pilsner","notes":"Light, smooth, gentle hop bite"},
  {"name":"Weihenstephaner Hefeweissbier","style":"hefeweizen","notes":"Banana, clove, fluffy classic Bavarian wheat"},
  {"name":"Weihenstephaner Hefeweissbier Dunkel","style":"dunkelweizen","notes":"Banana, caramel, toasty dark wheat"},
  {"name":"Weihenstephaner Korbinian","style":"doppelbock","notes":"Dark malt, caramel, robust"},
  {"name":"Weihenstephaner Original Helles","style":"helles","notes":"Soft malt, gentle honeyed sweetness, clean finish"},
  {"name":"Weihenstephaner Pils","style":"german-pilsner","notes":"Crisp, floral noble hops, dry finish"},
  {"name":"Weihenstephaner Tradition Dunkel","style":"munich-dunkel","notes":"Rich malt, caramel, toasty"},
  {"name":"Weihenstephaner Vitus","style":"weizenbock","notes":"Pale, strong, banana, spicy clove"},
  {"name":"WeldWerks Juicy Bits","style":"neipa","notes":"Citrus, tropical, creamy haze"},
  {"name":"Westbrook Gose","style":"gose","notes":"Bright lemon tartness, coriander, sea salt"},
  {"name":"Westmalle Dubbel","style":"dubbel","notes":"Dark fruit, caramel, classic Trappist"},
  {"name":"Westmalle Tripel","style":"tripel","notes":"Golden, fruity, peppery, dry benchmark"},
  {"name":"Widmer Brothers Hefe","style":"american-wheat","notes":"Cloudy, citrusy Pacific Northwest original"},
  {"name":"Wittekerke Belgian White","style":"witbier","notes":"Light, lemony, easy-drinking Flanders wit"},
  {"name":"Young's Double Chocolate Stout","style":"milk-stout","notes":"Rich chocolate, sweet, smooth"},
  {"name":"Yuengling Lager","style":"american-lager","notes":"Amber, toasty malt, smooth finish"},
  {"name":"Yuengling Porter","style":"porter","notes":"Mild roast, caramel, easy-drinking"}
];
